baseURL = "https://ratheronfire.com/"
languageCode = "en-us"
title = "Ratheronfire's Assorted Collection of Odd Projects"
theme = ["ratheronfire-theme", "hugo-easy-gallery"]
enableGitInfo = true

[frontmatter]
  date = ['original_date', 'date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
[taxonomies]
  category = "categories"
  tag = "tags"
  original-tags = "original-tags"
[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']