baseURL = "https://ratheronfire.com/"
languageCode = "en-us"
title = "Ratheronfire's Assorted Collection of Odd Projects"
theme = ["ratheronfire-theme", "hugo-easy-gallery"]
enableGitInfo = true
timeZone = "America/New_York"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        title = true
        level = true

[build]
  [build.buildStats]
    enable = true
[[build.cachebusters]]
    source = 'assets/watching/hugo_stats\.json'
    target = 'styles\.css'
[[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[[build.cachebusters]]
    source = 'assets/.*\.(js|ts|jsx|tsx)'
    target = 'js'
[[build.cachebusters]]
    source = 'assets/.*\.(.*)$'
    target = '$1'

[frontmatter]
  date = ['original_date', 'date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']

[taxonomies]
  category = "categories"
  tag = "tags"
  original-tags = "original-tags"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']