name: Deploy to neocities

# only run on changes to master
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "15 0/4 * * *"

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.126.1

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    # - name: Exiftool Scrub
    #   uses: TheGroundZero/exiftool-scrub@v1.2.0
    #   continue-on-error: true

    - name: Generate RSS feed
      run: python hugo-neocities/scripts/generate_rss_feed.py

    - name: Install Hugo CLI
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb

    - name: Install Dart Sass
      run: sudo snap install dart-sass

    - name: Install Node.js dependencies
      run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

    - name: Build with Hugo
      env:
        # For maximum backward compatibility with Hugo modules
        HUGO_ENVIRONMENT: production
        HUGO_ENV: production
      run: |
        hugo \
          -s hugo-neocities \
          --gc \
          --minify \
          --baseURL "${{ steps.pages.outputs.base_url }}/"

    - name: Rename 404 page
      # Hugo expects the 404 page to be 404.html, but Neocities uses not_found.html.
      run: mv "hugo-neocities/public/404.html" "hugo-neocities/public/not_found.html"

    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@master
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: hugo-neocities/public